### ISSUE TITLE
Spec link is 404

### ISSUE THREAD

**Issue by benvanik** [nvpro-samples/gl_commandlist_basic#1]
The link to the spec in the readme (http://www.opengl.org/registry/specs/NV/command_list.txt) is 404. I found https://developer.nvidia.com/sites/default/files/akamai/opengl/specs/GL_NV_command_list.txt - is that the latest and greatest?

**Comment by pixeljetstream** [comment]
Yes it is, though should just take a few days that this link works, too.
Am 22.03.2015 12:34 schrieb "Ben Vanik" notifications@github.com:

**Comment by benvanik** [comment]
Cool, thanks!
